lib/mechanize/page.rb

Currently when creating Nokogiri parser, the url is not passed to its initialize method.
I have some special needs for url in the Nokogiri object.
I am not sure if it was intentional to pass nil, however tests did pass.

Pass uri information to Nokogiri if available.

---

examples/rubygems.rb

rubyforg isn't available anymore, so i've changed the url, and then the formular instructions

Update examples/rubyforge (to rubygems)

---

mechanize.gemspec

Not a big whoop but hey, little things.

Remove deprecated rubyforge_project attribute

---

Rakefile

Fixes Issue #398
Please note that it fails CI checks because it now runs ALL of the tests (that weren't run previously) — and one of your tests fails!

Issue #398: Making sure ALL test files are ran, not just the first one!

---

lib/mechanize/http/www_authenticate_parser.rb
test/test_mechanize_http_www_authenticate_parser.rb

As reported in #450, a bad formated WWW-Authenticate with whitespace result in loop.
Simple Basic auth, whitespace used in auth-param assignment, see testcase
http://greenbytes.de/tech/tc/httpauth/#simplebasicwsrealm
All current browsers pass the case as valid and so should mechanize.

As reported in #450, WWW-Authenticate with whitespace result in loop

---

CHANGELOG.rdoc
lib/mechanize/http/agent.rb
test/test_mechanize_http_agent.rb

Redirect to a file URL may make it easier for remote attackers to obtain sensitive information or cause a DoS.
/cc @leejarvis

Don't allow redirect from a non-file URL to a file URL for security reasons

---

lib/mechanize/http/auth_realm.rb
test/test_mechanize.rb
test/test_mechanize_http_auth_challenge.rb
test/test_mechanize_http_auth_realm.rb
test/test_mechanize_http_auth_store.rb
test/test_mechanize_http_www_authenticate_parser.rb

This PR fixes issue #458: Basic authentication fails when specifying credentials for a realm that contains uppercase characters.
This PR adds various tests for case sensitivity in realm name and fixes the issue itself.
All tests pass with this fix.

Fix issue #458: Basic authentication fails when specifying credentials for a realm that contains uppercase characters

---

.travis.yml

The RVM alias jruby-19mode is outdated (JRuby 1.7.19)
JRuby 9.1 is the active branch
JRuby 1.7 is maintained with no EOL announced

Update JRuby versions for testing in travis-ci

---

CHANGELOG.rdoc
lib/mechanize/form.rb
lib/mechanize/form/multi_select_list.rb
lib/mechanize/history.rb
lib/mechanize/unauthorized_error.rb
test/test_mechanize.rb

This includes a fix for the bug (#333) that Encoding::CompatibilityError is raised when a file name is non-ASCII, and some optimizations to reduce string generation and copy in form data encoding.

Improve form encoding

---

CHANGELOG.rdoc
lib/mechanize/element_matcher.rb
lib/mechanize/form.rb
lib/mechanize/form/field.rb
lib/mechanize/form/multi_select_list.rb
lib/mechanize/form/option.rb
lib/mechanize/page/frame.rb
test/htdocs/find_link.html
test/test_mechanize_form.rb
test/test_mechanize_form_check_box.rb
test/test_mechanize_form_multi_select_list.rb
test/test_mechanize_link.rb
test/test_mechanize_page.rb

They would work for such elements as links and images, but never for forms, form fields and frames.
This fixes #444.

Make element(s)_with(search: selector) work as advertised

---

.travis.yml
Gemfile
README.rdoc

This PR organizes the Travis build matrix so that it's possible to add specific ENV vars to specific Rubies (without making the ENV settings global, nor turning them into a build combination for each Ruby).
- JRuby builds: add `env` with `JRUBY_OPTS=--debug`
- add 2.4.0 to matrix - it builds green
- update JRuby 9.1.5.0 to latest stable - 9.1.7.0
- use a Bundler v1.13.7
- 1.9.3 and 2.0.0 now build green - using the `ruby RUBY_VERSION` marker in the Gemfile

Travis: Rubies updated, add 2.4.0, fix 2.0.0, 1.9.3; update to jruby-9.1.7.0, add JRUBY_OPTS=--debug 

---

lib/mechanize/test_case/http_refresh_servlet.rb
lib/mechanize/test_case/infinite_refresh_servlet.rb
test/test_mechanize.rb
test/test_mechanize_cookie.rb
test/test_mechanize_cookie_jar.rb
test/test_mechanize_file_response.rb
test/test_mechanize_form_encoding.rb
test/test_mechanize_page_image.rb
test/test_mechanize_page_link.rb
test/test_mechanize_page_meta_refresh.rb
test/test_mechanize_util.rb

This cleans up all deprecation warnings from minitest. It still has failures (matching master) and warnings from mechanize deprecations (which I've disabled for this output):
```
10008 % rake
/Users/ryan/.rbenv/versions/2.4.2/bin/ruby -w -I"lib" -I"/Users/ryan/.gem/repos/mechanize/gems/rake-12.3.0/lib" "/Users/ryan/.gem/repos/mechanize/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/test_mechanize.rb" "test/test_mechanize_cookie.rb" "test/test_mechanize_cookie_jar.rb" "test/test_mechanize_directory_saver.rb" "test/test_mechanize_download.rb" "test/test_mechanize_element_not_found_error.rb" "test/test_mechanize_file.rb" "test/test_mechanize_file_connection.rb" "test/test_mechanize_file_request.rb" "test/test_mechanize_file_response.rb" "test/test_mechanize_file_saver.rb" …
```

Clean up tests for minitest 5 deprecations.

---

lib/mechanize/test_case/http_refresh_servlet.rb
lib/mechanize/test_case/infinite_refresh_servlet.rb
test/test_mechanize.rb

These test changes avoid testing the internals of `net-http-persistent` to unblock an update of the gem. See https://github.com/sparklemotion/mechanize/pull/499#issuecomment-365286603 for further background.

Fix net http persistent tests

---

lib/mechanize/http/agent.rb
test/test_mechanize_http_agent.rb

`identity` is a valid `content-encoding` header value https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
Fixes https://github.com/sparklemotion/mechanize/issues/385

Accept content-encoding identity

---

lib/mechanize/http/www_authenticate_parser.rb
test/test_mechanize_http_www_authenticate_parser.rb

As reported in #441, the `Mechanize::HTTP::WWWAuthenticateParser` parser gets stuck in a loop
in some cases when the WWW-Authenticate header is malformed.
The string scanner will continue to loop if it has not reached the end of the header string AND if the remainder of the string does not contain a recognisable auth-scheme.
This PR changes the behaviour such that it  will break out of the loop if the remaining header string is not recognisable (rather than getting stuck in a loop).

Prevent malformed WWW-Authenticate headers from causing infinite loops

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/11/08/jruby-9-1-14-0.html
Also: JRuby 1.7.27 is updated.

Travis: update JRuby to latest jruby-9.1.14.0, jruby-1.7.27

---

lib/mechanize/http/content_disposition_parser.rb
test/test_mechanize_http_content_disposition_parser.rb
test/test_mechanize_parser.rb

`ContentDispositionParser#parse` does not correctly parse the content disposition header when the filename has escaped quotes. In my case, the header was 
```
attachment; filename="\"G.I. Jive 1944\".mp3"; filename*=UTF-8''%22G.I.%20Jive%201944%22.mp3
```
According to [RFC 2616](https://tools.ietf.org/html/rfc6266#section-4.1), this is a valid header.
---------
I moved this fork into a new repository so I am closing #492 in favor of this. It would be great if this could be reviewed so that we do not have to rely on our fork.

parse filename that starts with an escaped quote

---

lib/mechanize/http/agent.rb

This is a possible solution for issue https://github.com/sparklemotion/mechanize/issues/512 where Mechanize is forcing `http://` into the string, even if it was provided.
I don't know how far back in ruby versions things like `=~` and `%r(regex)` go, so if these need to be changed to get better backwards compat, I'm all ears!

Only prepend http:// if it wasn't provided

---

lib/mechanize/page.rb
test/test_mechanize_page.rb

As in #493 described, Mechanize currently returns the concatinated text of all found `<title>` tags, even if they belong to SVG or RDF subcontent. This PR changes this behaviour, so only the expected HTML-title is returned.

#493 multiple titles

---

.travis.yml

This PR makes the CI matrix smaller and newer.
- updates the CI matrix to use latest JRuby, 9.2.5.0. [JRuby 9.2.5.0 release blog post](https://www.jruby.org/2018/12/06/jruby-9-2-5-0.html)
- Then, having read about the CI matrix changes in Nokogiri (which was failing this PR on JRuby 1.7), I changed this PR to also update all the other minor versions.
---
About the setting in Travis: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

CI: JRuby 9.2.5.0; drop defunct Travis setting

---

.travis.yml
Gemfile
mechanize.gemspec

This is an (experimental) PR to see if we can simplify away a few of the steps and comments in the Travis configuration.

CI: Using default script directive, allow Bundler to pick the gems needed

---

lib/mechanize/form.rb
test/test_mechanize_form.rb

We shouldn't try to submit empty strings to the server, since browsers
also simply ignore these fields
Fixes #536

Ignore fields without names in Form#build_query

---

test/test_mechanize.rb
test/test_mechanize_http_agent.rb

Net::HTTP::Persistent removed `#retry_change_requests` in v4.0.0 and
later, so these tests fail if we've pulled in a more recent version
than that.
Related to https://github.com/drbrain/net-http-persistent/pull/100

test: conditionally skip depending on net-http-persistent < v4

---

CHANGELOG.rdoc
mechanize.gemspec

Add webrick to development dependecies

---

lib/mechanize/test_case/gzip_servlet.rb
test/test_mechanize.rb
test/test_mechanize_form_keygen.rb
test/test_mechanize_http_agent.rb

- skip PKI test that fails because of openssl behavior differences
- update the GzipServlet to ensure the response sent is un-compressable
- remove unused variable to quash a warning

Make JRuby green

---

CHANGELOG.rdoc
lib/mechanize.rb
lib/mechanize/cookie_jar.rb
lib/mechanize/download.rb
lib/mechanize/file.rb
lib/mechanize/file_response.rb
lib/mechanize/test_case.rb
lib/mechanize/test_case/gzip_servlet.rb
lib/mechanize/test_case/verb_servlet.rb
test/test_mechanize.rb
test/test_mechanize_cookie_jar.rb
test/test_mechanize_download.rb
test/test_mechanize_file.rb
test/test_mechanize_file_response.rb

Prevent OS command injection

---

lib/mechanize/http/agent.rb

It seems to be `require 'kconv'` (Kanji converter in the standard Ruby libraries) is not used anywhere at all.
This found in truffle-ruby which hasn't been `kconv` yet in this issue https://github.com/oracle/truffleruby/issues/1439
This thing was introduced in this commit https://github.com/sparklemotion/mechanize/commit/5c8e802f35d53c355e4840c972ba0113f15b58e2

Remove unused kconv require

---

CHANGELOG.rdoc
lib/mechanize/http/agent.rb
test/test_mechanize_http_agent.rb

Credential headers (Authorization and Cookie) are now forwarded to cross-site when redirection. Should be cleared these headers before redirection to protect leaking credential info.

Clear credential headers when redirecting to cross site

---

CHANGELOG.rdoc
lib/mechanize/http/content_disposition_parser.rb
test/test_mechanize_http_content_disposition_parser.rb

Some websites incorrectly use ISO 8601 for the dates, causing an exception to be raised and rendering all other correctly specified fields unusable.

Add fallback to ISO 8601 date format in `ContentDispositionParser`.

---

mechanize.gemspec

`require_relative` is available since at least ruby 2.1 so not compatibility issue since mechanize require ruby 2.5+

gemspec: unclutter the requirement

---

test/test_mechanize_page_encoding.rb

An encoding test for buggy behavior related to libxml <= 2.9.10 does not pass with libxml >= 2.9.11, which was introduced in Nokogiri v1.11.4.

fix failing encoding test in CI

---

.github/workflows/ci-test.yml

The specific intention here is to be able to discern whether a failing job is due to rubocop or due to functional failures.

ci: split out rubocop as an initial job

---

mechanize.gemspec

@flavorjones
There is high severity security issue about addressable 2.7.0 and below: https://github.com/advisories/GHSA-jxhc-q857-3j6g
So update required addressable to 2.8

Update required version of addressable to 2.8

---

lib/mechanize.rb

Hi,
The Linux Firefox user-agent is pretty old right now, and mechanize being rejected automatically when using it on some sites.
Updated to current revision 94.0.
(=> SEC.gov (== AkamaiGHost) will reject requests automatically using the current Linux Firefox user agent).

updates Linux Firefox user-agent to rev94

---

lib/mechanize/cookie_jar.rb

see related https://github.com/sparklemotion/http-cookie/pull/34

use safe_load when using Psych >= 3.1

---

lib/mechanize/http/agent.rb
test/test_mechanize_http_agent.rb

Note that in this case we treat cookies differently from credentials
per RFC 6265 section 8.5:
https://datatracker.ietf.org/doc/html/rfc6265#section-8.5
> Cookies do not provide isolation by port.  If a cookie is readable
> by a service running on one port, the cookie is also readable by a
> service running on another port of the same server.  If a cookie is
> writable by a service on one port, the cookie is also writable by a
> service running on another port of the same server.  For this
> reason, servers SHOULD NOT both run mutually distrusting services on
> different ports of the same host and use cookies to store security-
> sensitive information.
@kyoshidajp, would love your feedback on this.

fix: clear credentials when redirecting to a different port

---

.github/workflows/ci-test.yml
test/test_mechanize_http_agent.rb
test/test_mechanize_page_link.rb

- Update CI to test with Ruby 3.2
- Pin JRuby until the frozen string fix in https://github.com/jruby/jruby/issues/7481 is released
- Skip NTLM tests for modern OpenSSL installations
- Run the tests in a weekly cron job to prevent bitrot going forward

ci: include ruby 3.2, get back to green

---

.github/workflows/ci-test.yml

ci: use latest bundler

---

.github/workflows/ci-test.yml
CHANGELOG.md
README.md
mechanize.gemspec

ruby 2.5 started failing in CI again, and I just don't have the energy to try to fix it.
https://github.com/sparklemotion/mechanize/actions/runs/4382526288/jobs/7741821736#step:3:346
It's time.

drop ruby 2.5 support

---

lib/mechanize/page.rb
test/test_mechanize_page.rb

which allows us to handle frozen strings
This is an alternative solution to the problem described in #609

fix: stop force_encoding the page body

---

.github/workflows/ci-test.yml

To quash the node 12 warnings.

ci: update actions/checkout version

---

test/test_mechanize_page_link.rb

libxml2 versions 2.11.0..2.11.4 do not recover from some encoding errors. the upcoming release will change the encoding of the resulting doc as a result of recovery changes in libxml2.
See https://gitlab.gnome.org/GNOME/libxml2/-/issues/543 for more context.
Closes #613

test: work around libxml2 encoding changes

---

test/test_mechanize_page_link.rb

For example of a failing test, see https://github.com/sparklemotion/mechanize/actions/runs/6195521653/job/16840196792

ci: test_mechanize_page_link requires nokogiri before using it

---

.github/workflows/ci-test.yml
test/test_mechanize_http_agent.rb

Add Ruby 3.3 to the test matrix.
Also, update an encoding test to pass with the latest libxml2 (v2.12) delivered by the latest nokogiri (v1.16).

ci: test with ruby 3.3, accommodate new libxml2 behavior

---

CHANGELOG.md
lib/mechanize.rb
lib/mechanize/form.rb
lib/mechanize/form/multi_select_list.rb
lib/mechanize/http/agent.rb
lib/mechanize/http/content_disposition_parser.rb
lib/mechanize/page.rb
test/test_mechanize_cookie_jar.rb
test/test_mechanize_form.rb

This PR aims to fix various minor typos across the codebase. I noticed some of these when doing the same review on our Homebrew/brew repo, since we use mechanize.

various: fix miscellaneous typos

---

examples/latest_user_agents.rb
lib/mechanize.rb

This PR aims to facilitate the updating of `Mechanize::AGENT_ALIASES`. 
It can more easily update by generating output from `examples/latest_user_agents.rb` with the same structure as `Mechanize::AGENT_ALIASES`.
In addition, I update User-Agent strings to represent modern browser version.
Below is the result of running the script `examples/latest_user_agents.rb`:
```bash
$ ruby examples/latest_user_agents.rb
fetch chrome UA...
sleeping... (1s)
fetch firefox UA...
sleeping... (1s)
fetch safari UA...
sleeping... (1s)
fetch edge UA...
sleeping... (1s)
{"Linux Firefox"=>"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/121.0",
"Mac Firefox"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 14.2; rv:109.0) Gecko/20100101 Firefox/121.0",
"Mac Safari"=>"Mozilla/5.0 (Macintosh; …
```

More easily update Mechanize::AGENT_ALIASES

---

.github/workflows/ci-test.yml
mechanize.gemspec

Explicitly add gems that are unbundled in Ruby 3.4 (that Ruby 3.3 is already warning about):
- nkf is used directly by mechanize
- base64 is used by rubyntlm but that gem does not look maintained
Also: add `truffleruby` (stable) and `jruby-head` to the CI matrix.
Fixes #633

dep: ruby 3.4 unbundled gems

---

lib/mechanize.rb
lib/mechanize/cookie.rb
test/test_mechanize_cookie.rb
test/test_mechanize_http_agent.rb
test/test_mechanize_page_link.rb

Mechanize has still been using `Kernel#caller` whose string representation has changed enough in Ruby 3.4.0.dev to break how deprecation messages were being handrolled.
Replace all uses of `caller` with `caller_locations` which is both faster and returns an object with some nice methods we can use to isolate the method, the file, and the line number.
This should get us green again on ruby-head.

prefer `caller_locations` and `Thread::Backtrace::Location` methods to `Kernel#caller`

---

.github/workflows/ci.yml
.github/workflows/upstream.yml

update CI pipelines
- update versions of actions
- drop macos and windows builds (which are low value for this gem)
- split out testing of edge rubies to "upstream" pipeline
- add upstream nokogiri integration test

ci: extract upstream pipeline, start integration testing against nokogiri main

---

lib/mechanize/page.rb
test/test_mechanize_page_link.rb

Starting with libxml2 v2.12.0, encoding errors have a message that was not being detected by Page#encoding_error? resulting in a page that was parsed using incorrect encoding.
This change updates Page to detect those errors as _encoding errors_ and as a result we get the expected encoding back on the parsed document.

fix: correctly recognize encoding errors in libxml >= 2.12.0

---

CHANGELOG.md
lib/mechanize/http/agent.rb
test/test_mechanize_http_agent.rb

See #646 for discussion.
Closes #647.

tidy: do not send the deprecated `accept-charset` header

---

CHANGELOG.md
Gemfile
lib/mechanize/http/agent.rb
mechanize.gemspec
test/test_mechanize_http_agent.rb

Add support for Brotli compression

---

lib/mechanize/test_case.rb

It broke in CI where the TERM env var is not set, see minitest/minitest#1009

test: don't use minitest/pride

---

Gemfile
lib/mechanize/http/agent.rb
test/test_mechanize_http_agent.rb

Just like #650 (adds brotli compression), this PR aims to give Mechanize support for Zstandard (zstd), in a similar way (will only work if you have the zstd-ruby gem installed).

Add Zstd support (optional dependency, just like Brotli)

---

lib/mechanize/pluggable_parsers.rb
mechanize.gemspec

mime-types 3.6.0 warns "MIME::Type.MIME::Type.new when called with a String is deprecated."
change introduced in and syntax borrowed from:
https://github.com/mime-types/ruby-mime-types/commit/8512c1544e9b4a292284865c4d0c2b04e126fcc7

fix: mime type string deprecation

---

.github/workflows/ci.yml
.github/workflows/upstream.yml

Dropping jruby and truffleruby from the test matrix.
We can add them back if they restabilize, but recently these tests have been very very noisy and simultaneously they are low value. And I am tired.

ci: drop jruby and truffleruby, add 3.4

---

CHANGELOG.md
lib/mechanize/util.rb

by using URI::RFC23996_PARSER directly if it exists.

quash Ruby 3.4 URI::Parser warnings

---

CHANGELOG.md
lib/mechanize.rb
lib/mechanize/http/agent.rb
test/test_mechanize.rb

Re-instantiation of #586, with some additional tests
cc @maurycy

Support Net::HTTP::Persistent.write_timeout

---

.github/workflows/ci.yml
.github/workflows/upstream.yml

Wondering if it's OK to add TruffleRuby back (both the last release and head). It was removed in a7f9461bbccafdb858d8ac706316adb1e4e7c6b8. Tests pass now (see https://github.com/andrykonchin/mechanize/pull/1).

Restore TruffleRuby in CI

---

test/htdocs/frame_test.html
test/htdocs/relative/tc_relative_links.html

In HTML5, frames/noframes content is raw text, not PCDATA; and libxml2 has implemented this behavior in v2.14.

test: update test documents to remove markup from frames/noframes
